### ISSUE TITLE
python -m pip install . error

### ISSUE THREAD

**Issue by monusk111** [TannerGilbert/Tensorflow-Object-Detection-API-Train-Model#10]
ERROR: Command errored out with exit status 1:
     command: 'C:\Users\mskak\AppData\Local\Programs\Python\Python37\python.exe' -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\mskak\\AppData\\Local\\Temp\\pip-install-s5ovt5o5\\pycocotools\\setup.py'"'"'; __file__='"'"'C:\\Users\\mskak\\AppData\\Local\\Temp\\pip-install-s5ovt5o5\\pycocotools\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record 'C:\Users\mskak\AppData\Local\Temp\pip-record-ngx97fie\install-record.txt' --single-version-externally-managed --compile --install-headers 'C:\Users\mskak\AppData\Local\Programs\Python\Python37\Include\pycocotools'
         cwd: C:\Users\mskak\AppData\Local\Temp\pip-install-s5ovt5o5\pycocotools\
    Complete output (21 lines):
    running install
    running build
    running build_py
    creating build
    creating build\lib.win-amd64-3.7
    creating build\lib.win-amd64-3.7\pycocotools
    copying pycocotools\coco.py -> build\lib.win-amd64-3.7\pycocotools
    copying pycocotools\cocoeval.py -> build\lib.win-amd64-3.7\pycocotools
    copying pycocotools\mask.py -> build\lib.win-amd64-3.7\pycocotools
    copying pycocotools\__init__.py -> build\lib.win-amd64-3.7\pycocotools
    running build_ext
    skipping 'pycocotools\_mask.c' Cython extension (up-to-date)
    building 'pycocotools._mask' extension
    creating build\temp.win-amd64-3.7
    creating build\temp.win-amd64-3.7\Release
    creating build\temp.win-amd64-3.7\Release\common
    creating build\temp.win-amd64-3.7\Release\pycocotools
    C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.27.29110\bin\HostX86\x64\cl.exe /c /nologo /Ox /W3 /GL /DNDEBUG /MD -IC:\Users\mskak\AppData\Local\Programs\Python\Python37\lib\site-packages\numpy\core\include -I./common -IC:\Users\mskak\AppData\Local\Programs\Python\Python37\include -IC:\Users\mskak\AppData\Local\Programs\Python\Python37\include "-IC:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.27.29110\include" "-IC:\Program Files (x86)\Windows Kits\NETFXSDK\4.7.2\include\um" /Tc./common/maskApi.c /Fobuild\temp.win-amd64-3.7\Release\./common/maskApi.obj
    maskApi.c
    ./common/maskApi.c(8): fatal error C1083: Cannot open include file: 'math.h': No such file or directory
    error: command 'C:\\Program Files (x86)\\Microsoft Visual Studio\\2019\\Community\\VC\\Tools\\MSVC\\14.27.29110\\bin\\HostX86\\x64\\cl.exe' failed with exit status 2
    ----------------------------------------
ERROR: Command errored out with exit status 1: 'C:\Users\mskak\AppData\Local\Programs\Python\Python37\python.exe' -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\mskak\\AppData\\Local\\Temp\\pip-install-s5ovt5o5\\pycocotools\\setup.py'"'"'; __file__='"'"'C:\\Users\\mskak\\AppData\\Local\\Temp\\pip-install-s5ovt5o5\\pycocotools\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record 'C:\Users\mskak\AppData\Local\Temp\pip-record-ngx97fie\install-record.txt' --single-version-externally-managed --compile --install-headers 'C:\Users\mskak\AppData\Local\Programs\Python\Python37\Include\pycocotools' Check the logs for full command output.

**Comment by TannerGilbert** [comment]
On windows you have to install pycocotools differently: https://github.com/cocodataset/cocoapi/issues/169#issuecomment-462528628
