### ISSUE TITLE
Issue when: 4. Generating Training data

### ISSUE THREAD

**Issue by yo0x** [TannerGilbert/Tensorflow-Object-Detection-API-Train-Model#11]
Hi Tanner,
generate_tfrecord.py in section number 4 ( Generating Training data) Dat Tran’s raccoon detector, it
 address tf 1.x. while your code addresses tf2.x. 
Generates: 
Traceback (most recent call last):
File "csv_a_tf.py", line 24, in
flags = tf.app.flags
AttributeError: module 'tensorflow' has no attribute 'app'

i recommend updating the reference to another repo (maybe https://github.com/douglasrizzo/detection_util_scripts)
Best regards
yo0x

**Comment by TannerGilbert** [comment]
I updated the readme as requested. Thanks for pointing out that the section wasn't up-to-date anymore.
