### ISSUE TITLE
Issue while installing python -m pip install .

### ISSUE THREAD

**Issue by fasrinaleem** [TannerGilbert/Tensorflow-Object-Detection-API-Train-Model#12]
![issue](https://user-images.githubusercontent.com/38991771/102930553-aa832e00-44c2-11eb-8809-a1610f27713d.PNG)
![python version](https://user-images.githubusercontent.com/38991771/102930558-abb45b00-44c2-11eb-9e50-17a37536e04f.PNG)

**Comment by TannerGilbert** [comment]
Hard to say what the issue is.

Maybe try updating pip:
```
pip install --upgrade pip
```

Also maybe try to install `avro-python3` before running `python -m pip install .`

``` 
pip install avro-python3
```
