### ISSUE TITLE
training issue

### ISSUE THREAD

**Issue by RMC-G** [TannerGilbert/Tensorflow-Object-Detection-API-Train-Model#16]
**Describe the bug**
fails when trying to run training, successful following of the rest of the guide
I have search online and not found any solution to
** ImportError: libGL.so.1: cannot open shared object file: No such file or directory**

![image](https://user-images.githubusercontent.com/66533812/104388874-09701c00-5532-11eb-989f-2a76a3710506.png)

**Comment by TannerGilbert** [comment]
Maybe try out the [this](https://github.com/conda-forge/pygridgen-feedstock/issues/10#issuecomment-365914605).

**Comment by RMC-G** [comment]
Thanks I added the following code to the top of the docker file and it fixed the issue!

RUN apt-get update && \
    apt-get install libgl1-mesa-glx -y
