### ISSUE TITLE
path to label_map

### ISSUE THREAD

**Issue by RMC-G** [TannerGilbert/Tensorflow-Object-Detection-API-Train-Model#18]
Having changed all lines in the config file, when I run the training i get the following error which makes me think there is another label map path being called? 

![image](https://user-images.githubusercontent.com/66533812/104488741-b2685680-55c6-11eb-833e-70f46f08e715.png)

this is my input
![image](https://user-images.githubusercontent.com/66533812/104488827-d330ac00-55c6-11eb-9b76-64509821ae94.png)

**Comment by TannerGilbert** [comment]
Duplicate of #17
