### ISSUE TITLE
Created a script to run inferences on the test images and display in OpenCV window

### ISSUE THREAD

**Issue by youngsoul** [TannerGilbert/Tensorflow-Object-Detection-API-Train-Model#19]
First - **thank you** for putting together your YouTube video and this repo.  It definitely helped a lot to get started with understanding how to use Tensorflow2 Object Detection.

I wanted to share a script I put together to run inferences and display the results locally using opencv windows.  You can find a gist of my script here:

https://gist.github.com/youngsoul/ae49b39e35cc66d34d564958dda66f35

**Comment by TannerGilbert** [comment]
Nice work, thank you. I also have scripts to run inference on images, videos, or a camera stream in one of [my other repositories](https://github.com/TannerGilbert/Tensorflow-Object-Detection-with-Tensorflow-2.0), which you can check out if you're interested.
