### ISSUE TITLE
Question:  If I restart the training, will the training start off from the last checkpoint?

### ISSUE THREAD

**Issue by youngsoul** [TannerGilbert/Tensorflow-Object-Detection-API-Train-Model#20]
Hi Tanner 

Like you in your video, I stopped the training and tested the predictions.  I was not happy with the results so I want to restart the training.

It looks like it restarts from the last checkpoint but it was not clear to me if that was the case from the tensor board.

Thanks again for a great blog post and repo to learn from.

**Comment by youngsoul** [comment]
I am going to answer my own question.  After letting a restart run for a while - I can say it picks up at a checkpoint.  

It seems to oscillate initially but it will settle in pretty close to where it let off.

**Comment by nikhilparmar** [comment]
> I am going to answer my own question. After letting a restart run for a while - I can say it picks up at a checkpoint.
> 
> It seems to oscillate initially but it will settle in pretty close to where it let off.

Thank you for your answer. Can you please tell me how to retrain on top of the earlier trained model. I have the same issue, your answer will help me a lot. Thanks.
