### ISSUE TITLE
Error during the installation process

### ISSUE THREAD

**Issue by poorya7** [TannerGilbert/Tensorflow-Object-Detection-API-Train-Model#24]
**Describe the bug**
I get lots of error during the installation process, when I execute the python install command. 
![err](https://user-images.githubusercontent.com/5989680/112754737-6b75e480-8fab-11eb-961d-0d09abc94216.png)

**To Reproduce**
 I've been following it step by step but when I run the command python -m pip install . halfway through its execution I get a bunch of errors in red and it exits. Errors say things like Connection closed and .. .I've been struggling with it for a while and nothing works. I've attached a screenshot of the errors. 

**Desktop (please complete the following information):**
 - OS: Windows 10
- Python version: 3.7.0
- Protoc version: protoc-3.15.6-win64

**Comment by TannerGilbert** [comment]
I couldn't reproduce this error on my Windows machine (Python 3.8.8). I found a [question on Stackoverflow](https://stackoverflow.com/questions/66140105/keyerror-when-installing-tensorflow), but I'm not sure if this will help fix this error.

**Comment by poorya7** [comment]
I think this might be a library compatibility issue, or version issue, because I was trying another tutorial which was very similar to yours, and in that one, instead of the command **python -m pip install .** the tutorial suggested to use the command  **python setup.py install** and when I try that, half way through it, the process exits with : fatal error C1083: Cannot open include file: 'math.h': No such file or directory. I attached a screenshot!

![fatal](https://user-images.githubusercontent.com/5989680/112760066-ab48c600-8fc3-11eb-97ca-9e469478a0ef.png)

Any ideas how I can resolve it? 
Thanks again Gilbert.

**Comment by poorya7** [comment]
after a long day I finally managed to solve it. 
What worked for me was to uninstall and re-install the Visual C++ 2015 build tools. It can be found here: [https://go.microsoft.com/fwlink/?LinkId=691126](url)
