### ISSUE TITLE
ImportError: cannot import name 'abs'

### ISSUE THREAD

**Issue by 4lparslan** [TannerGilbert/Tensorflow-Object-Detection-API-Train-Model#25]
When i execute this command "python object_detection/builders/model_builder_tf2_test.py" i get an error like this.

**Comment by TannerGilbert** [comment]
Take a look at the following related issues/questions:
* [ImportError: cannot import name 'abs'](https://github.com/tensorflow/tensorflow/issues/20778)
* [ImportError: cannot import name 'abs'](https://stackoverflow.com/questions/51299194/importerror-cannot-import-name-abs/51771078)

**Comment by 4lparslan** [comment]
> 
> 
> Take a look at the following related issues/questions:
> 
>     * [ImportError: cannot import name 'abs'](https://github.com/tensorflow/tensorflow/issues/20778)
> 
>     * [ImportError: cannot import name 'abs'](https://stackoverflow.com/questions/51299194/importerror-cannot-import-name-abs/51771078)

I am using Windows and i can't solve the problem. On Stackoveflow this solution is for Linux systems:

pip uninstall tensorflow protobuf --yes
find $CONDA_PREFIX -name "tensorflow" | xargs -Ipkg rm -rfv pkg
pip install --ignore-installed --upgrade https://storage.googleapis.com/tensorflow/linux/cpu/tensorflow-1.9.0-cp36-cp36m-linux_x86_64.whl --no-cache-dir

**Comment by 4lparslan** [comment]
i also tried to reinstall tensorflow and protobuf but not changed

**Comment by TannerGilbert** [comment]
The following could work on Windows:
* https://github.com/tensorflow/tensorflow/issues/20778#issuecomment-410962482
* https://github.com/tensorflow/tensorflow/issues/20778#issuecomment-405007806
