### ISSUE TITLE
using tensorflow-gpu

### ISSUE THREAD

**Issue by 4lparslan** [TannerGilbert/Tensorflow-Object-Detection-API-Train-Model#26]
With "python -m pip install ." command we install tensorflow but not tensorflow-gpu. How can i use it?

**Comment by TannerGilbert** [comment]
For Tensorflow 2, you don't need to install `tensorflow-gpu` explicitly anymore. Instead it's automatically detecting if you have a compatible GPU when installing tensorflow with `pip install tensorflow`.

For more information, check out the [GPU support documentation](https://www.tensorflow.org/install/gpu#pip_package).
