### ISSUE TITLE
File "...\site-packages\tensorflow\python\training\py_checkpoint_reader.py", line 48, in error_translator     raise errors_impl.OpError(None, None, error_message, errors_impl.UNKNOWN) tensorflow.python.framework.errors_impl.OpError: not an sstable (bad magic number)

### ISSUE THREAD

**Issue by danicamariromero** [TannerGilbert/Tensorflow-Object-Detection-API-Train-Model#29]
Hi, I followed your article but got this error. I think there is something wrong with the checkpoint file? Are there other steps needed before I'd be able to use the model from http://download.tensorflow.org/models/object_detection/tf2/20200711/mask_rcnn_inception_resnet_v2_1024x1024_coco17_gpu-8.tar.gz?

I changed this line.
fine_tune_checkpoint: "training/mask_rcnn_inception_resnet_v2_1024x1024_coco17_gpu-8/checkpoint/ckpt-0"

Thanks!

**Comment by seanbenhur** [comment]
Does the colab notebook works now!?
I have a  similar error

**Comment by TannerGilbert** [comment]
Sorry for the late reply. I have a [dedicated repository for training an Instance Segmentation model](https://github.com/TannerGilbert/Tensorflow-Object-Detection-API-train-custom-Mask-R-CNN-model/blob/master/Tensorflow_Object_Detection_API_Instance_Segmentation_in_Google_Colab.ipynb). You should be able to train your own custom Mask-RCNN with that code.
