### ISSUE TITLE
Does the docker file work on the Mac?

### ISSUE THREAD

**Issue by Shoshin23** [TannerGilbert/Tensorflow-Object-Detection-API-Train-Model#3]
Firstly, thank you for making a very 2020-easy-to-setup version of the Tensorflow Object Detection API. Most tutorials make the setup process a huge pain in the ass. 

I'm trying to run your docker file on my mac. Does it not work on a Mac? I'm getting the following error when I let docker-compose up run fully: 

```
Successfully built 9365a006aa6c
Successfully tagged docker_tensorflow_object_detection_api:latest
Creating tensorflow_object_detection_api ... error

ERROR: for tensorflow_object_detection_api  Cannot create container for service tensorflow_object_detection_api: Unknown runtime specified nvidia

ERROR: for tensorflow_object_detection_api  Cannot create container for service tensorflow_object_detection_api: Unknown runtime specified nvidia
ERROR: Encountered errors while bringing up the project.
```

Can this only be run on Linux machines or can it be run on the Mac as well.

**Comment by TannerGilbert** [comment]
The error occurs because of the base image (nvidia/cuda:10.1-cudnn7-devel), which only works if you have an NVIDIA GPU and have [nvidia-docker](https://github.com/NVIDIA/nvidia-docker) installed. Most MACs have a AMD GPU therefore you want be able to train it on your GPU. Rather you'll have to use another base image like Ubuntu or Debian.

I'll create a README that makes this more clear soon.

**Comment by Shoshin23** [comment]
So, in short, it's not possible to run the Docker container on my Mac? Or is there a workaround you suggest. Also, I'm open to trying out a CPU-only version. 

Thank you!

**Comment by TannerGilbert** [comment]
Yeah there is a very simple workaround. You just need to replace the base image (the first line of the Dockerfile).

Something like the following should work
 ```
FROM ubuntu:16.04

RUN apt-get update && apt-get upgrade -y

RUN apt-get install -y git

RUN apt-get install -y python3 && apt-get install -y python3-pip

RUN update-alternatives --install /usr/bin/python python /usr/bin/python3.6 1

# Installing the Tensorflow Object Detection API (https://gilberttanner.com/blog/installing-the-tensorflow-object-detection-api)
RUN git clone --depth 1 https://github.com/tensorflow/models.git

# Install object detection api dependencies
RUN DEBIAN_FRONTEND=noninteractive apt-get install -y protobuf-compiler python3-pil python3-lxml python3-tk && \
    pip3 install Cython && \
    pip3 install contextlib2 && \
    pip3 install jupyter && \
    pip3 install matplotlib && \
    pip3 install tensorflow==1.14.0

# Install pycocoapi
RUN git clone --depth 1 https://github.com/cocodataset/cocoapi.git && \
    cd cocoapi/PythonAPI && \
    make -j8 && \
    cp -r pycocotools /models/research && \
    cd ../../ && \
    rm -rf cocoapi

# Get protoc 3.0.0, rather than the old version already in the container
RUN apt-get install -y curl unzip

RUN curl -OL "https://github.com/google/protobuf/releases/download/v3.0.0/protoc-3.0.0-linux-x86_64.zip" && \
    unzip protoc-3.0.0-linux-x86_64.zip -d proto3 && \
    mv proto3/bin/* /usr/local/bin && \
    mv proto3/include/* /usr/local/include && \
    rm -rf proto3 protoc-3.0.0-linux-x86_64.zip

# Run protoc on the object detection repo
RUN cd models/research && \
    protoc object_detection/protos/*.proto --python_out=.

# Set the PYTHONPATH to finish installing the API
ENV PYTHONPATH=$PYTHONPATH:/models/research/slim
ENV PYTHONPATH=$PYTHONPATH:/models/research

# Entrypoint
WORKDIR /models/research/object_detection
ENTRYPOINT ["jupyter", "notebook", "--ip=0.0.0.0", "--no-browser", "--allow-root"]
```

If you experience any problems with this be sure to let  me know. I'll add the README as soon as possible.

**Comment by Shoshin23** [comment]
Should I also modify the docker-compose.yml file? The error i get now is: 

```
WARNING: The DISPLAY variable is not set. Defaulting to a blank string.
Creating tensorflow_object_detection_api ... error

ERROR: for tensorflow_object_detection_api  Cannot create container for service tensorflow_object_detection_api: Unknown runtime specified nvidia

ERROR: for tensorflow_object_detection_api  Cannot create container for service tensorflow_object_detection_api: Unknown runtime specified nvidia
```

Thank you!

**Comment by TannerGilbert** [comment]
Yes you also need to remove the runtime in the docker-compose.yml file.

I just created a cpu version, which you can find in the docker folder. I also added a README as well as a shell file that automatically determines if you have a GPu and opens the right docker image.

Please try it out and let me know if it works.

Kind regards,
Gilbert Tanner

**Comment by TannerGilbert** [comment]
Just tested both the GPU and CPU version on both Windows and Linux and it works fine for me. Normally it should work on MAC as well without any issue. 

If it works for you be sure to let me know and to close the issue.

**Comment by Shoshin23** [comment]
So, the docker file runs when l remove the runtime line in the yaml file. 

In the end the method that worked best for me was using Google Colab. Minimum setting up to do and was able to train my model without any hassles.

**Comment by TannerGilbert** [comment]
Yeah Google Colab is great. I'll close this issue now. If you experience any further issues be free to reopen it.
