### ISSUE TITLE
What is image_show !?

### ISSUE THREAD

**Issue by seanbenhur** [TannerGilbert/Tensorflow-Object-Detection-API-Train-Model#30]
For the code for saving the bounding boxes, I want to know what is meant by `image_show` in the 7th line !?

```
output_directory = 'some dir'

# get label and coordinates of detected objects
output = []
for index, score in enumerate(output_dict['detection_scores']):
    label = category_index[output_dict['detection_classes'][index]]['name']
    ymin, xmin, ymax, xmax = output_dict['detection_boxes'][index]
    output.append((label, int(xmin * image_width), int(ymin * image_height), int(xmax * image_width), int(ymax * image_height)))

# Save images and labels
for l, x_min, y_min, x_max, y_max in output:
    array = cv2.cvtColor(np.array(image_show), cv2.COLOR_RGB2BGR)
    image = Image.fromarray(array)
    cropped_img = image.crop((x_min, y_min, x_max, y_max))
    file_path = output_directory+'/images/'+str(len(df))+'.jpg'
    cropped_img.save(file_path, "JPEG", icc_profile=cropped_img.info.get('icc_profile'))
    df.loc[len(df)] = [datetime.datetime.now(), file_path]
    df.to_csv(output_directory+'/results.csv', index=None

**Comment by TannerGilbert** [comment]
The code is copied from the [another script](https://github.com/TannerGilbert/Tutorials/blob/master/Tensorflow%20Object%20Detection/surveillance.py#L100). `image_show` should be the input image. If you're using the Tensorflow 2 scripts from the [Tensorflow-Object-Detection-with-Tensorflow-2.0 repo](https://github.com/TannerGilbert/Tensorflow-Object-Detection-with-Tensorflow-2.0/blob/master/detect_from_video.py) like the  replace it with [detect_from_video.py script](https://github.com/TannerGilbert/Tensorflow-Object-Detection-with-Tensorflow-2.0/blob/master/detect_from_video.py) replace it with `image_np`.

**Comment by seanbenhur** [comment]
Thank you, I have replaced it, but it still works different, when I save an image, only half of the predicted region is saved, but I would like to save all the predicted regions.

I have described my issue [here](https://discuss.tensorflow.org/t/saving-the-predicted-images-of-bounding-boxes-tensorflow-object-detection-api/2085) also

**Comment by TannerGilbert** [comment]
I have created a Tensorflow 2 example: https://github.com/TannerGilbert/Tensorflow-Object-Detection-with-Tensorflow-2.0/blob/master/extract_detections_from_camera.py

**Comment by seanbenhur** [comment]
Thanks a lot!😍
