### ISSUE TITLE
Error in the testing the installation run

### ISSUE THREAD

**Issue by AravindSadashiv1998** [TannerGilbert/Tensorflow-Object-Detection-API-Train-Model#32]
Hi,
After installing and running `python -m pip install .` command, I run the command, `python object_detection/builders/model_builder_tf2_test.py` to test the installation. But I'm getting the following errors as seen in the image attached below.
I'm currently running it in a Virtual Machine in GCP which contains a GPU . So when I run the `pip install -U tensorflow==2.3.0` command, it runs but still shows some errors and messes up my GPU , due to which I'm not able to access it.

Please any help will be much appreciated!

Best,
Aravind
![ERROR](https://user-images.githubusercontent.com/73475583/130632706-f5bc8b81-112d-4be3-a4a7-4944252c0cce.png)

**Comment by TannerGilbert** [comment]
I just took a look, and it seems that the Dockerfiles really are quite old. They're still using Tensorflow 2.2, but according to the setup.py script, at least version 2.5 is required. It works for more with both Tensorflow 2.5 and 2.6.
