### ISSUE TITLE
accuracy calculation

### ISSUE THREAD

**Issue by nisarggandhewar** [TannerGilbert/Tensorflow-Object-Detection-API-Train-Model#5]
Is their any command to get accuracy of model that I have created using tensorflow 1.13 for custom object.

**Comment by TannerGilbert** [comment]
There isn't a accuracy metric like for image classification for object detection. You can check out the available metrics by taking a look at the evaluation_protocols.md file: https://github.com/tensorflow/models/blob/master/research/object_detection/g3doc/evaluation_protocols.md
