### ISSUE TITLE
Colab notebook training errors

### ISSUE THREAD

**Issue by jjdisplay** [TannerGilbert/Tensorflow-Object-Detection-API-Train-Model#7]

**Comment by jamesee** [comment]
Hi, 

I took your colab notebook and ran at Colab. The training could not proceed... error messages as follow:

I do not know how to proceed from here, please assist.

====================
Errors may have originated from an input operation.
Input Source operations connected to node EfficientDet-D0/functional_1/stack_5/block_1/expand_conv2d/Conv2D:
 EfficientDet-D0/functional_1/stack_5/block_0/id/Identity (defined at /local/lib/python3.6/dist-packages/official/modeling/activations/swish.py:75)

Input Source operations connected to node EfficientDet-D0/functional_1/stack_5/block_1/expand_conv2d/Conv2D:
 EfficientDet-D0/functional_1/stack_5/block_0/id/Identity (defined at /local/lib/python3.6/dist-packages/official/modeling/activations/swish.py:75)

Function call stack:
_dist_train_step -> _dist_train_step
